### ISSUE TITLE
Scegliere una licenza

### ISSUE THREAD

**Issue by VaiTon** [cartabinaria/upld#12]
Opterei per la MIT, visto che ne vogliamo diffondere l'uso e alla fine non è un grande sforzo implementativo.

Altrimenti si potrebbe considerare la AGPL.

@lucat1

**Comment by VaiTon** [comment]
@lucat1 e @bogo8liuk va bene la licenza AGPL?

**Comment by foxyseta** [comment]
So che sono estraneo alla cosa ma al momento usiamo la AGPL per il software nelle altre repository (se non in tutte quasi).

**Comment by bogo8liuk** [comment]
Direi che AGPL va benissimo, eviterei MIT per lo stesso motivo che ha menzionato foxy
